lesson 5 commit
JacinthaDev/Backend-ruby-testfirst pull request #1
Opened 2024-07-06 21:51 UTC by JacinthaDev

2024-07-11 16:36 UTC, gacurl requested changes
need a book_titles_spec.rb file before concluding the exercise.

2024-07-11 16:36 UTC, gacurl commented on 02_calculator/calculator_spec.rb
Your tests are comprehensive and cover various scenarios for each method (multiply, power, and factorial)! weel done

2024-07-11 16:36 UTC, gacurl commented on 03_simon_says/simon_says_spec.rb
Your tests cover different scenarios for each method defined in simon_says.rb, ensuring their functionality is thoroughly checked

2024-07-11 16:36 UTC, gacurl commented on 04_pig_latin/pig_latin_spec.rb
To create a functional translate method for Pig Latin, follow these steps:

Splitting Input: Start by splitting the input string into individual words using split.

Vowel and Consonant Recognition: Define an array vowels containing all vowel characters (both uppercase and lowercase) to check against. Use regular expressions to identify specific consonant clusters like "qu" and "sch".

Translation Logic: For each word:

Check if it starts with a vowel using start_with? and vowels.
If it starts with a vowel, simply append "ay" to the end of the word.
If it starts with consonants or a recognized consonant cluster:
Use slice! to remove the consonants or cluster from the beginning of the word.
Append the removed segment followed by "ay" to the end of the word.
Preserve capitalization by checking and applying the same casing to the translated word as the original.
Handling Multiple Words: After translating each word, join them back into a single string with spaces.

2024-07-11 16:36 UTC, gacurl commented on 04_pig_latin/pig_latin_spec.rb
this is tough:

try this code:
`def translate(string)
  words = string.split

  vowels = %w[a e i o u A E I O U]
  pig_latin = words.map do |word|
    if word.start_with?(/^[aeiou]/i) # starts with a vowel
      word + "ay"
    elsif word =~ /^(qu|sch)/i # starts with 'qu' or 'sch'
      consonants = word.slice!(/^(qu|sch)/i)
      word + consonants + "ay"
    else # starts with consonants
      consonants = word.slice!(/^[^aeiou]+/)
      word + consonants + "ay"
    end
  end

  pig_latin.join(" ")
end`

2024-07-11 16:36 UTC, gacurl commented on 05_book_titles/book.rb
where is the test code? the book_rspec.rb file

2024-07-22 02:51 UTC, JacinthaDev commented on 05_book_titles/book.rb
I think the book_rspec.rb file isn't showing in my PR because that file wasn't altered. There were no changes we had to make to that file.

2024-07-25 22:14 UTC, merged